### ISSUE TITLE
[Question] Latest Tailwind Version

### ISSUE THREAD

**Issue by smhmd** [nuxt-community/tailwindcss-module#116]
Using `Nuxt-tailwind` with `create-nuxt-app`, the tailwind version used is `1.2.0`, two and a half minor versions behind the current `1.4.6` version. (They're not that minor.)

Why not use the latest version automatically instead of requiring a [bump](https://github.com/nuxt-community/tailwindcss-module/commit/e15ded4c8a41cac9202c1fee555cdf3d006a43fd) every now and then? If something breaks, encouraging issues would help? Are there any other drawbacks to that?

(I'm not a node dev, so I could be misunderstanding somethin.)

**Comment by nielsdB97** [comment]
This should not be needed because of [the use of `^` (caret) matcher](https://github.com/nuxt-community/tailwindcss-module/blob/09c0ee570c9e21c53864a1466f49552dc48a35c7/package.json#L28). This will install any minor version of the `1` major. You can find more information [here](https://docs.npmjs.com/about-semantic-versioning).
