### ISSUE TITLE
@apply with classes included in cssPath

### ISSUE THREAD

**Issue by Maiquu** [nuxt-community/tailwindcss-module#123]
### Version
@nuxtjs/tailwindcss: v1.4.1
nuxt: v2.12.2

### Reproduction Link
https://codesandbox.io/s/nuxt-tailwindcss-pzbvo

### Steps to reproduce
1) Insert any class after `@import 'tailwindcss/utilities'` at `cssPath`
2) Use that class in `@apply` expression under SFC `<styles lang="postcss">` tag

### What is Expected?
`@apply` expression to know classes that are added by plugins (or at the file located at `cssPath`)

### What is actually happening?
```
Module build failed (from ./node_modules/postcss-loader/src/index.js): SyntaxError (40:0) `@apply` cannot be used with `.flex-center` because `.flex-center` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.flex-center` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

**Comment by ahsandev2019** [comment]
get same error 
(42:3) `@apply` cannot be used with `.flex-center` because `.flex-center` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.flex-center` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

i jsut copy the https://codesandbox.io/s/o4vn5pvp7q
but i get same error

**Comment by ahsandev2019** [comment]
i dont know why, its solved by disable prettier, installing new with eslint only is working and no error

**Comment by hacknug** [comment]
As I mentioned in #140, I think here's how you could work around the issue: https://github.com/nuxt-community/tailwindcss-module/issues/140#issuecomment-689618395

**Comment by Atinux** [comment]
Please upgrade to the lastest version of this module and re-open if the issue still persist.
