### ISSUE TITLE
New _tailwind route not compatible with i18n

### ISSUE THREAD

**Issue by jankal** [nuxt-community/tailwindcss-module#220]
### Version
@nuxtjs/tailwindcss: 3.3.1
nuxt: 2.14.9

### Reproduction Link
Click on https://codesandbox.io/s/optimistic-noether-qko1j and navigate to `/_tailwind` in the CodeSandbox browser.

### Steps to reproduce
1. Set up a fresh project with `@nuxtjs/tailwindcss`
2. Install `nuxt-i18n` into the project
3. Add config for `nuxt-i18n` (don't know if this is required)

### What is Expected?
No console output on navigation to `/_tailwind`.

### What is actually happening?
The following error is printed to the console when accessing `/_tailwind`
```
 WARN  [vue-router] Route with name '_tailwind___en' does not exist
```

**Comment by bcs-gbl** [comment]
Try this one:

`
['nuxt-i18n', {
  parsePages: false,
  pages: {
    _tailwind: false
  }
}]
`

**Comment by jankal** [comment]
@bcs-gbl tried in one of my projects. Unfortunately it doesn't work.

**Comment by jankal** [comment]
Thanks @Atinux! I just didn't want some newbie to get scared.

**Comment by rchl** [comment]
This is triggered by VueRouter because `nuxt-i18n` tries to lookup a non-existing route to see if it exists.

I can't see any workaround or fix for it now. I believe fixing this would require fixing https://github.com/nuxt-community/i18n-module/issues/984 first. That would allow us to have a code path that avoids route resolving when we know for sure that route doesn't exist.
