### ISSUE TITLE
Background Gradient

### ISSUE THREAD

**Issue by Ethan-Hill** [nuxt-community/tailwindcss-module#223]
### Is your feature request related to a problem? Please describe.

I was trying to use bg-gradient-to-r from-red-400 to-blue-500 and realised its not working
### Describe the solution you'd like

I would like background gradient support for tailwindcss-module
### Describe alternatives you've considered

Using pure css

**Comment by azrikahar** [comment]
Can you provide more details for your project/environment? Just to clarify, this module only makes it easier to integrate Tailwind CSS. It won't do things such as not supporting gradient when Tailwind does. Whatever Tailwind has, your Nuxt project should have it as well.

Here are two screenshots showing that it is working on a fresh Nuxt project:

### Project

![Code_yHDau3qmQK](https://user-images.githubusercontent.com/42867097/101321251-0c774d00-38a0-11eb-9c0a-631ca3487b15.png)

### Result

![chrome_TGBRuoQuqF](https://user-images.githubusercontent.com/42867097/101321242-097c5c80-38a0-11eb-8431-6b20b3ec8e31.png)

Note: Couldn't create a codesandbox for the above environment since I upgraded to Tailwind v2 (refer here: https://tailwindcss.nuxtjs.org/setup#tailwind-2). Tailwind v2 requires `Node >= 12.13.0` whereas codesandbox is still on Node 10 by default.

**Comment by Ethan-Hill** [comment]
### **Project**
![Code_Fqg7G54bFH](https://user-images.githubusercontent.com/45304268/101332809-b7224800-386d-11eb-91e8-0929ddf7b018.png)
### **Result**
![opera_mThlS17cj3](https://user-images.githubusercontent.com/45304268/101331928-8f7eb000-386c-11eb-8ae5-86b5564f5dba.png)

Seems like we have nearly the same project dependencies, i just have a few extra for other

**Comment by Ethan-Hill** [comment]
This was fixed with a tailwind config change,

My colors were not in extend.

```module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  theme: {
    extend: {
      colors: {
        bg: '#121212',
        spotify: '#1ed760',
        navbg: '#040404',
        playerbg: '#282828',
        white: '#FFFFFF'
      }
    }
  },
  variants: {},
  plugins: []
}
```
