### ISSUE TITLE
Responsive and regular classes stripped with PurgeCSS in production build

### ISSUE THREAD

**Issue by musayev-io** [nuxt-community/tailwindcss-module#248]
### Version

@nuxtjs/tailwindcss: 3.4.2
nuxt: 2.14.7

### Reproduction Link

https://github.com/musayev-io/musa-blog

### Notes

When building my site in production, a bunch of my TailwindCSS classes are being stripped. I've discovered that all responsive classes are not working `sm: | md: ...`, as well as standard classes such as `py-X`, `list-decimal`, `list-disc`, and who knows what else. 

If I whitelist certain patterns (such as below) in my `tailwind.config.js`, I can get those classes working in production. However, this can't be the expected behavior. There may be many more classes down the road that get purged that  I would never notice.

```javascript
  purge: {
    options: {
      whitelist: ['list-decimal', 'list-disc', 'list-inside'],
      whitelistPatterns: [/^p[x,y]-/, /^p-/]
}
```

My project is pretty vanilla, so I don't believe this is due to any configuration errors on my end. Here are some screenshots:

![Development - Everything Working](https://user-images.githubusercontent.com/41654718/104985126-db795480-59d5-11eb-9046-d8077cd265e3.png)

![Production - Classes stripped](https://user-images.githubusercontent.com/41654718/104985130-e0d69f00-59d5-11eb-8c83-bab07871703c.png)

**Comment by azrikahar** [comment]
Hi, replied your question in the tailwind discord server, but I figured it's better to add context here for anyone finding this issue in the future.

Currently the suspicion is since the classes such as `list-decimal` that are being whitelisted exists inside your `/app/prismic/html-serializer.js`, we'll need to add this into the purge content array as seen here: https://tailwindcss.nuxtjs.org/tailwind-config

hope that resolves the issue.

**Comment by musayev-io** [comment]
@azrikahar - Good eye! I think that's what the overarching problem is. However, PurgeCSS doesn't appear to acknowledge those classes when I updated my config Tailwind config. Same behavior. 

```javascript
purge: {
    content: [
      'app/prismic/html-serializer.js',
    ]
}
```

**Comment by musayev-io** [comment]
It appears that this has something to do with file resolution when defining a custom `srcDir` in the `nuxt.config.js`. I see a closed issue #114, but it looks like there's still a use-case that needs to be ironed out. I moved the application out of `/src` and everything works fine.

**Comment by musayev-io** [comment]
I set it as `/src` and moved my `tailwind.config.js` inside there as well. When building, I would see `Merging Tailwind config from ~/tailwind.config.js` and the settings were being applied.

**Comment by luismarquesfreire** [comment]
This also have implications in using jit = true in the new version 4.0.1 as it purges as well in dev.

From Tailwindcss documentation (https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css):

"Your CSS is identical in development and production. Since styles are generated as they are needed, you don't need to purge unused styles for production, which means you see the exact same CSS in all environments. Never worry about accidentally purging an important style in production again."
