### ISSUE TITLE
[BUG] JIT doesn't build styles on cold start

### ISSUE THREAD

**Issue by eggsy** [nuxt-community/tailwindcss-module#298]
### Version
@nuxtjs/tailwindcss: 4.0.1
nuxt: 2.15.3

### Reproduction Link
[https://github.com/eggsy/website](https://github.com/eggsy/website)

### Steps to reproduce
- Enable JIT mode by putting `{ jit: true }` in `nuxt.config.js > tailwindcss`.
- Start or build your app.
- See the result (no classes are actually built, the page doesn't include any styles).

### What is Expected?
Should parse the class names and include them in the output file.

### What is actually happening?
Seems like it's not able to read class names on the initial/cold start. It works and able to parse classes on HMR (when you edit a page/component/layout) and applies styles.

I've actually posted this before the v4 was merged with #287 but it got merged without me getting a "proper" answer. We have also discussed this on Nuxt.js' Discord guild ([click here to jump to message](https://discord.com/channels/473401852243869706/473406004751499275/821301861583683594)) and 2 other people reported the same issue. Tried some ways but couldn't find anything that actually fixes this issue. 

Maybe it's because I have a separate source dir, or something else. This also happened with Windi CSS and I thought it was a bug, now I started to think about this is an issue with Nuxt/PostCSS.

This is what happens at the first start:

![image](https://user-images.githubusercontent.com/13917975/111319719-5d54c980-8677-11eb-897d-f1ae77a13909.png)

This happens when I re-save (without any changes) my index.vue (grids and other classes on the page are built successfully):

![image](https://user-images.githubusercontent.com/13917975/111319823-73fb2080-8677-11eb-98bc-e5eca57efe72.png)

This is what happens when I re-save (again, without any changes) my layout, default.vue:

![image](https://user-images.githubusercontent.com/13917975/111319895-84130000-8677-11eb-84e1-83fe646b1087.png)

And re-saving my navbar and theme switch component:

![image](https://user-images.githubusercontent.com/13917975/111319956-92611c00-8677-11eb-9363-1621727a9b0d.png)

So, I was able to get my index page working by editing 4 different files, and it's not even fully working as expected. It gets reset when you build your app again...

**Comment by eggsy** [comment]
It strangely started working after a `yarn upgrade`.

**Comment by azrikahar** [comment]
> It strangely started working after a `yarn upgrade` today, don't know what happened.

Surprisingly `yarn upgrade` solved it for me as well. Just to provide more info, in my project with yarn workspaces, I did ran `yarn upgrade-interactive --latest` earlier and it only showed my backend has outdated package, not my frontend (which is Nuxt). So yea I'm not sure what happened since there shouldn't be any packages outdated for my frontend before `yarn upgrade` is ran. 

With that said, hopefully this bug is solved for good. Will report back if it occurs again.

**Comment by Neodark7** [comment]
sadly `npm update` didn't fixed it for my project..

**Comment by Atinux** [comment]
I highly recommend using Yarn for module resolution when we have to deal with nested modules dependencies.

```
rm -rf node_modules yarn.lock
yarn install
```

**Comment by RomainMazB** [comment]
Hi there!

I faced the exact same issue with npm. When I found this thread I hoped yarn could help but same results so I've searched deeper.

I finally found how to solve on my machine modifying the purge paths.

The one provided by tailwind it this one:
```js
exports = {
  purge: [
    './components/**/*.{vue,js}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}'
  ]
```
and this one worked for me:
```js
exports = {
  purge: [
    '~/components/**/*.{vue,js}',
    '~/layouts/**/*.vue',
    '~/pages/**/*.vue',
    '~/plugins/**/*.{js,ts}',
    '~/nuxt.config.{js,ts}'
  ]
```

I think the issue is related to the nuxt paths resolver.

Can you test it @Neodark7
