### ISSUE TITLE
HMR reload twice with JIT

### ISSUE THREAD

**Issue by ewilan-riviere** [nuxt-community/tailwindcss-module#369]
I'm not sure it's a bug, it's cause by JIT. When I enable JIT from `tailwind.config.js` like this

```js
module.exports = {
  mode: 'jit',
}
```

And when I update any .vue file, HMR reload twice, I suppose the first for JIT because browser not update itself, I can see changements with second reload. Maybe it's my config but I don't found how to fix this, if it's a bug.

In my `package.json`

```json
{
    "devDependencies": {
      "@nuxtjs/tailwindcss": "^4.2.0",
    }
}
```

I try to install fresh project but I've always this problem. When I disable JIT, HMR reload only one time and everything is okay. I know JIT is in preview but if anyone has a tip to fix this, thanks!

**Comment by atlesque** [comment]
Likely a duplicate of #357

**Comment by HenrijsS** [comment]
Same issue here. 
Everything works fine with `@nuxtjs/tailwindcss: 4.2.1` (Latest as of 17.07.2021)
The problem is if the `tailwindcss` version is greater than `2.1.0`

I'm going to check the tailwind repo for notable changes but HMR works completely fine with `2.1.0` and I didn't see any notable bugs while developing. Will comment upon some errors.

**Comment by ewilan-riviere** [comment]
It works now for me too. Thanks for your comment, I will close this issue, everything is okay :)

**Comment by HenrijsS** [comment]
@ewilan-riviere Well this isn't a permanent fix. 
Tailwind 2.2 features a lot of great features which are now absent.
