### ISSUE TITLE
Overriding child component classes

### ISSUE THREAD

**Issue by apgapg** [nuxt-community/tailwindcss-module#392]
https://stackoverflow.com/questions/62529550/overriding-tailwind-css-classes-in-a-reusable-vuejs-component

With ref to above if I have a component as:

```
<template>
  <button
    :disabled="disabled"
    class="
      px-3
      py-1.5
      text-white text-sm
      bg-blue-500
      hover:bg-blue-600
      font-medium
      rounded
    "
    @click="onButtonClick"
  >
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'PrimaryButton',
  props: {
    disabled: { type: Boolean, default: false, required: false },
  },
  methods: {
    onButtonClick() {
      this.$emit('click')
    },
  },
}
</script>

```

and if I try using it as below

```
<PrimaryButton class="bg-red-500" @click="onClick">
              Sign in
 </PrimaryButton>
```

There is no effect of `bg-red-500` on the button.

Is there any easy way to do that?

**Comment by hacknug** [comment]
> There is no effect of `bg-red-500` on the button.
> 
> Is there any easy way to do that?

Far from ideal but you could do a few things:
- Use `!bg-red-500` instead so it is more specific than the class on your component
- Move the button color to a prop with a default value of `bg-blue-500`
- Add `bg-blue-500` conditionally only when there is no class that contains `bg-` (this kinda sucks because you could be trying to make the background clip or something but then you'd get no bg-color)
- Use custom properties on your component. `.bg-button` could inherit the color from it's instance and fallback to blue when it is not defined (might require you to make changes to core's `backgroundColor` plugin

**Comment by apgapg** [comment]
@hacknug Thank you for sharing your knowledge. Just wanted to know the best practice for above use case. Is there any standard approach to tackle such case?

**Comment by hacknug** [comment]
@apgapg I'd say go with the first one I mentioned if you only have one button that needs to be different. Go with the second if there's multiple buttons on your codebase that need to be styled differently. The other suggestions would work but might not be the best implementations or the easiest to tackle if you don't have much experience writing custom plugins and such.

**Comment by apgapg** [comment]
Thanks @hacknug for your words. Closing the issue
